import type { NextPage } from "next";
import Head from "next/head";
import HeaderContainer from "../components/HeaderContainer";
import ContactContainer from "../components/main/ContactContainer";
import HomeSectionContainer from "../components/main/HomeSectionContainer";
import { user } from "../db/user";

const Contact: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="lm-bg"></div>
        <div className="page">
          <div className="page-content">
            <HeaderContainer user={user} />
            <main>
              <div className="content-area">
                <div className="animated-sections">
                  <ContactContainer user={user} />
                </div>
              </div>
            </main>
          </div>
        </div>
      </>
    </div>
  );
};

export default Contact;
