import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import AuthContainer from "../components/auth/AuthContainer";
import AuthTemplate from "../components/auth/AuthTemplate";
import RegisterContainer from "../components/auth/RegisterContainer";
import HeaderContainer from "../components/HeaderContainer";
import Loader from "../components/LoaderContainer";
import HomeSectionContainer from "../components/main/HomeSectionContainer";
import { useCurrentUserQuery, User } from "../generated/graphql";

const Home: NextPage = () => {
  const [user, setUser] = useState<User>();
  const [token, setToken] = useState("");
  const { isLoading, isError, data, error, refetch } = useCurrentUserQuery<any>(
    {},
    { refetchOnWindowFocus: false }
  );

  useEffect(() => {
    if (token !== "") {
      refetch();
    }
    if (data?.currentUser) {
      setUser(data.currentUser);
    }
  }, [token, data]);

  if (isLoading) {
    return (
      <Loader />
    );
  }
  if (isError || user?._id === undefined) {
    return (
      <AuthTemplate setUser={setUser} setToken={setToken} />
    );
  }

  return (
    <div>
      <Head>
        <title>Generate your online CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="lm-bg"></div>
        <div className="page">
          <div className="page-content">
            {user !== undefined && <HeaderContainer user={user} setToken={setToken} setUser={setUser}/>}
            <main>
              <div className="content-area">
                <div className="animated-sections">
                  {user && <HomeSectionContainer user={user} />}
                </div>
              </div>
            </main>
          </div>
        </div>
      </>
    </div>
  );
};

export default Home;
