import type { NextPage } from "next";
import Head from "next/head";
import HeaderContainer from "../components/HeaderContainer";
import PortfolioSectionContainer from "../components/main/PortfolioSectionContainer";
import { user } from "../db/user";

const Portfolio: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="lm-bg"></div>
        <div className="page">
          <div className="page-content">
            <HeaderContainer user={user} />
            <main>
              <div className="content-area">
                <div className="animated-sections">
                  {user.portfolio && <PortfolioSectionContainer portfolio={user.portfolio} />}
                </div>
              </div>
            </main>
          </div>
        </div>
      </>
    </div>
  );
};

export default Portfolio;
