import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import HeaderContainer from "../components/HeaderContainer";
import ResumeSectionContainer from "../components/main/ResumeSectionContainer";
import { useCurrentUserQuery, User } from "../generated/graphql";

const Resume: NextPage = () => {

  const [user, setUser] = useState<User>()
  const {data} = useCurrentUserQuery<any>({}, {
    refetchOnWindowFocus: false
  })

  useEffect(() => {
    if(data?.currentUser){
      setUser(data.currentUser);
    }
  }, [data])


  const componetForRendering = (user: User) => {
    if (user.personalPath && user.abilities) {
      return (
        <ResumeSectionContainer
          paths={user.personalPath}
          abilities={user.abilities}
        />
      );
    } else if (user.personalPath && !user.abilities) {
      return <ResumeSectionContainer paths={user.personalPath} />;
    } else {
      return user.abilities && <ResumeSectionContainer abilities={user.abilities} />;
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="lm-bg"></div>
        <div className="page">
          <div className="page-content">
            {user && <HeaderContainer user={user} />}
            <main>
              <div className="content-area">
                <div className="animated-sections">
                  {user && componetForRendering(user)}
                </div>
              </div>
            </main>
          </div>
        </div>
      </>
    </div>
  );
};

export default Resume;
