import type { NextPage } from "next";
import Head from "next/head";
import HeaderContainer from "../components/HeaderContainer";
import ResumeSectionContainer from "../components/main/ResumeSectionContainer";
import { user } from "../db/user";
import { User } from "../interfaces/User";

const Resume: NextPage = () => {
  const componetForRendering = (user: User) => {
    if (user.personalPath && user.abilities) {
      return (
        <ResumeSectionContainer
          paths={user.personalPath}
          abilities={user.abilities}
        />
      );
    } else if (user.personalPath && !user.abilities) {
      return <ResumeSectionContainer paths={user.personalPath} />;
    } else {
      return <ResumeSectionContainer abilities={user.abilities} />;
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="lm-bg"></div>
        <div className="page">
          <div className="page-content">
            <HeaderContainer user={user} />
            <main>
              <div className="content-area">
                <div className="animated-sections">
                  {componetForRendering(user)}
                </div>
              </div>
            </main>
          </div>
        </div>
      </>
    </div>
  );
};

export default Resume;
