import type { NextPage } from "next";
import Head from "next/head";
import HeaderContainer from "../components/HeaderContainer";
import SettingsContainer from "../components/main/SettingsContainer";
import { useCurrentUserQuery } from "../generated/graphql";

const Settings: NextPage = () => {
  const { isLoading, isError, data, error, refetch } = useCurrentUserQuery(
    {},
    { refetchOnWindowFocus: false }
  );


  if (isLoading) {
    return (
      <div>
        <span>Loading...</span>
      </div>
    );
  }

  if (isError) {
    const msg = String(error);
    return (
      <div>
        <p>{msg}</p>
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>Settings for Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="lm-bg"></div>
        <div className="page">
          <div className="page-content">
            <HeaderContainer user={data?.currentUser} />
            <main>
              <div className="content-area">
                <div className="animated-sections">
                  <SettingsContainer user={data?.currentUser} />
                </div>
              </div>
            </main>
          </div>
        </div>
      </>
    </div>
  );
};

export default Settings;
