import Head from "next/head";
import { User } from "../../generated/graphql";
import AuthContainer from "./AuthContainer";
import RegisterContainer from "./RegisterContainer";

interface Props {
    setUser: (type: User) => void;
    setToken: (type: string) => void
}

const AuthTemplate: React.FC<Props> = ({setToken, setUser}) => {
    return (
        <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <div className="lm-bg"></div>
          <div className="page">
            <div className="page-content">
              <RegisterContainer />
              <main>
                <div className="content-area">
                  <div className="animated-sections">
                    <AuthContainer setToken={setToken} />
                  </div>
                </div>
              </main>
            </div>
          </div>
        </>
      </div>
    )
}

export default AuthTemplate;